import pandas as pd
import os

def process_interest_rates():
    input_file = 'raw-data/monthly_interest_rate_2023_2026.csv'
    output_dir = 'data/processed'
    output_file = f'{output_dir}/monthly_interest_rate_matrix_2023_2026.csv'

    os.makedirs(output_dir, exist_ok=True)

    print(f"Reading monthly interest rate time-series file...{input_file}...")
    
    if not os.path.exists(input_file):
        print(f"Error: File not found. Please ensure the file is saved exactly as {input_file}")
        return

    try:
        skip_lines = 0
        with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
            for i, line in enumerate(f):
                if 'REF_DATE' in line or '"REF_DATE"' in line:
                    skip_lines = i
                    break
        
        if skip_lines > 0:
            print(f"Statistics Canada metadata detected. Skipping the first {skip_lines} rows before processing...")
            
        df = pd.read_csv(input_file, skiprows=skip_lines)
        print(f"Successfully read! Raw data size: {df.shape[0]} rows, {df.shape[1]} columns")
        
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        return

    standard_cols = [
        'REF_DATE', 'GEO', 'DGUID', 'Seasonality', 'UOM', 'UOM_ID', 
        'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 
        'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS'
    ]
    
    category_col = next((col for col in df.columns if col not in standard_cols), None)
    
    if not category_col:
       # Fallback to 'Rates' if automatic detection fails
        category_col = 'Rates' if 'Rates' in df.columns else None

    if not category_col:
        print("Error: Unable to detect the Interest Rate Category column. Please verify the raw CSV structure.")
        return

    # Data Cleaning
    df_clean = df[['REF_DATE', category_col, 'VALUE']].copy()
    df_clean['VALUE'] = pd.to_numeric(df_clean['VALUE'], errors='coerce').fillna(0) 

    # Data Reshaping: Pivot to Time-Series Format
    print("\nPivoting data into a monthly interest rate time-series matrix...")
    try:
        df_matrix = df_clean.pivot_table(
            index='REF_DATE', 
            columns=category_col, 
            values='VALUE',
            aggfunc='first'
        ).reset_index()

        # Remove the column index name generated by the pivot operation
        df_matrix.columns.name = None

        print("\nTime-series reshaping completed successfully. Preview of the first 5 months:")
        pd.set_option('display.max_columns', None)
        print(df_matrix.head())

        df_matrix.to_csv(output_file, index=False)
        print(f"\nMonthly interest rate matrix saved successfully to:{output_file}")
        print("\nProceeding to process the final macroeconomic indicator: Consumer Price Index (CPI).")
    except Exception as e:
        print(f"\nError occurred during data reshaping:{e}")

process_interest_rates()